Remove pypy3 since its tests are failing
Traceback (most recent call last):
  File “…/bump/tests/test_bump.py”, line 14
    import pygogo as gogo
ImportError: No module named pygogo